### ISSUE TITLE
An error occurred (AuthFailure) when calling the DescribeInstances operation

### ISSUE THREAD

**Issue by hseagle2015** [awslabs/aws-ops-automator#29]
Hello,

I'm using Ops Automator v2.2 on primary account (in eu-central-1 region) and I'm using the Ec2ResizeInstance template for scheduled vertical scaling of an EC2 instance (with "replace by type" method) running on the secondary account.

The OpsAutomator Lambda function always fails when I try to perform EC2 instance resize for an EC2 instance running in **eu-south-1** (Milan) region.

On the same secondary account, the same Ops Automator task works fine in basically all the standard regions (e.g. eu-central-1, eu-west-1, eu-north-1 etc.).

This is the debug error message logged to the CloudWatch Logs on the primary account (AWS account number and some other values are anonimized):

```json
2023-02-10 - 10:24:02.907 - ERROR   : Error handling request 
{
    "action": "select-resources",
    "task": {
        "name": "mil-test-resize",
        "action": "Ec2ResizeInstance",
        "regions": [
            "eu-central-1",
            "eu-south-1"
        ],
        "this_account": false,
        "interval": "23 11 10 2 FRI",
        "events": {},
        "event_scopes": {},
        "timezone": "Europe/Paris",
        "select_size": "Standard",
        "select_ecs_memory": null,
        "execute_size": "Standard",
        "execute_ecs_memory": null,
        "completion_size": "Standard",
        "completion_ecs_memory": null,
        "timeout": 15,
        "tag_filter": null,
        "EventSourceTagFilter": null,
        "dryrun": false,
        "debug": true,
        "notifications": false,
        "enabled": true,
        "internal": false,
        "task_metrics": false,
        "accounts": [
            "XXXXXXXXXXXX"
        ],
        "cross_account_role": null,
        "description": "mil-test-resize",
        "parameters": {
            "InstanceTypes": [
                "t4g.small",
                "t4g.large"
            ],
            "ReplaceMode": "ReplaceByType",
            "AssumedType": "t4g.small",
            "TryNextInRange": true
        },
        "service": "ec2",
        "resource_type": "Instances"
    },
    "source": "scheduler-handler",
    "task-datetime": "2023-02-10T11:23:00+01:00",
    "task-group": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "sub-task": {
        "this_account": false,
        "accounts": [
            "XXXXXXXXXXXX"
        ],
        "regions": [
            "eu-south-1"
        ]
    }
}
 by handler SelectResourcesHandler: (ERR_SELECTING_TASK_RESOURCES : Error selecting resources for task mil-test-resize, 'ClientError' object has no attribute 'message')
Traceback (most recent call last):
  File "/var/runtime/bootstrap.py", line 480, in <module>
    main()
  File "/var/runtime/bootstrap.py", line 468, in main
    handle_event_request(lambda_runtime_client,
  File "/var/runtime/bootstrap.py", line 127, in handle_event_request
    response = request_handler(event, lambda_context)
  File "/var/task/boto_retry/aws_service_retry.py", line 175, in call
    resp = method(**used_call_arguments)
  File "/var/runtime/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AuthFailure) when calling the DescribeInstances operation: AWS was not able to validate the provided access credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/handlers/select_resources_handler.py", line 497, in handle_request
    all_resources = list(service.describe(self._resource_name,
  File "/var/task/services/aws_service.py", line 501, in describe
    raise ex
  File "/var/task/services/aws_service.py", line 493, in describe
    resp = describe_func(**function_args)
  File "/var/task/boto_retry/__init__.py", line 71, in wrapped_api_method
    return retry_strategy.call(client_or_resource, name, args)
  File "/var/task/boto_retry/aws_service_retry.py", line 186, in call
    if self.can_retry(ex):
  File "/var/task/boto_retry/ec2_service_retry.py", line 80, in can_retry
    return AwsApiServiceRetry.can_retry(self, ex)
  File "/var/task/boto_retry/aws_service_retry.py", line 127, in can_retry
    return any([rt(ex) for rt in self._call_retry_strategies])
  File "/var/task/boto_retry/aws_service_retry.py", line 127, in <listcomp>
    return any([rt(ex) for rt in self._call_retry_strategies])
  File "/var/task/boto_retry/aws_service_retry.py", line 50, in api_throttled
    return "throttling" in ex.message.lower()
AttributeError: 'ClientError' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/main.py", line 94, in lambda_handler
    result = handler.handle_request()
  File "/var/task/handlers/select_resources_handler.py", line 559, in handle_request
    raise_exception(ERR_SELECTING_TASK_RESOURCES, self.task[handlers.TASK_NAME], ex)
  File "/var/task/outputs/__init__.py", line 61, in raise_exception
    raise Exception(s)
Exception: ERR_SELECTING_TASK_RESOURCES : Error selecting resources for task mil-test-resize, 'ClientError' object has no attribute 'message'

{
    "Caller": "lambda_handler",
    "Module": "main",
    "Line": 97,
    "Code": "ERR_HANDLING_REQUEST"
}
```

**Comment by hseagle2015** [comment]
To answer my own question (and to help anyone else that encountered the same problem), the issue is related with the fact that new AWS regions (e.g. eu-south-1, asia-south-1, etc.) support only the updated version of session tokens, version 2.

Ops Automator is obtaining tokens from the global endpoint, which by default issue version 1 session tokens.

**SOLUTION 1**
[Change the compatibility of STS tokens](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html#sts-regions-manage-tokens), so that they are valid for all regions (not only the AWS regions enabled by default).
